### ISSUE TITLE
Why isn't this part of obsidian importer?

### ISSUE THREAD

**Issue by KraXen72** [MarcDonald/obsidian-day-one-importer#1]
https://github.com/obsidianmd/obsidian-importer

why is this needed as a separate plugin? I'm surprised nobody raised this concern during the PR to add it to the plugins store.

**Comment by MarcDonald** [comment]
> https://github.com/obsidianmd/obsidian-importer
> 
> 
> 
> why is this needed as a separate plugin? I'm surprised nobody raised this concern during the PR to add it to the plugins store.

Process reasons mainly, I initially made this as a quick script to try out Obsidian and then when I decided to make it public I didn't want to be restricted by the constraints of an existing project with it's own maintainers and processes and wanted the autonomy to release patches and features myself. 

I had also thought about features that would be cool to build that obsidian-importer doesn't support to my knowledge, like the ability to do scheduled daily imports, but that was more of a secondary reason.

**Comment by KraXen72** [comment]
okay, thanks for the explanation
