### ISSUE TITLE
Location co-ordinates in FrontMatter

### ISSUE THREAD

**Issue by MarcDonald** [MarcDonald/obsidian-day-one-importer#2]
**Is your feature request related to a problem? Please describe.**
Some other plugins allow you to place co-ordinates onto a map. If there are co-ordinates stored in a Day One entry, this information is currently lost when importing it into Obsidian using this plugin.

**Describe the solution you'd like**
Full location information stored in Day One entries is imported into the FrontMatter of the Obsidian markdown file when importing. This could be customisable via the settings to allow users to decide what type of location information is imported (location names, co-ordinates, how granular to go etc)

**Describe alternatives you've considered**
N/A

**Additional context**
It would be nice to have a feature where you could import a journal and add to the FrontMatter of files you have already imported, as you may have modified the imported files and don't want to override them - this may be a separate feature though and not a part of this depending on the additional complexity.

**Comment by RobertBreen-cyber** [comment]
Hi Marc - I'm curious to know  if this enhancement of including the latitude and longitude coordinates from Day One could be included in the Front Matter section as an option.  I've got 12 years worth of location data stored in Day One and would love to have that come over to Obsidian for use with the Map View plug-in. I sure love this plug-in.  Thanks!

**Comment by MarcDonald** [comment]
Hey @RobertBreen-cyber! I've just released [version 1.1.0](https://github.com/marcdonald/obsidian-day-one-importer/releases/1.1.0) which includes this functionality, as well as the ability to update the FrontMatter of already existing entries so you don't need to delete everything and re-import. 

Note that updating the FrontMatter is a destructive action that will overwrite the FrontMatter of any existing entries, so I'd recommend making a backup beforehand just to be safe.

Let me know if you run into any issues or if something doesn't quite fit your needs (e.g. co-ordinate formatting), glad the plugin is a help!

**Comment by RobertBreen-cyber** [comment]
Hey @MarcDonald! Thank you so much for adding this!  I was able to test this with about 100 journal entries from Day One.  With a little manipulation via BBEdit, I was able to see all these journal entries on an interactive map via Map View. My jaw literally dropped when I began interating with the map.  Really cool. The only request I would have is to combine the latitude and longitude into a single property element with a name like Lat-Long in a format like this: 

47.3692512512207,-122.43575286865234

That's the format needed for Map View, which can point to any property name as long as it follows the format above. 

Let me know this is possible.  Again THANK YOU so much!

**Comment by MarcDonald** [comment]
No problem @RobertBreen-cyber, I've made this the default behaviour in version 1.1.1 with an option to use separate fields if you'd prefer. You can use the "Update FrontMatter" functionality to populate this across your entries.

Default behaviour:
![Screenshot of the frontmatter field with co-ordinates combined into one field](https://github.com/user-attachments/assets/ad6ced48-46e1-407b-a0a4-96c6b8da4c44)

With separate co-ordinate fields option selected:
![Screenshot of the frontmatter field with co-ordinates in separate latitude and longitude fields](https://github.com/user-attachments/assets/037ded23-1492-4e41-b376-518be4475f5c)

I just noticed as I type this that I included a space after the comma in the coordinate fields (e.g `-5, 10` instead of `-5,10`), if this causes an issue with Map View let me know and I will fix it ASAP

**Comment by RobertBreen-cyber** [comment]
Hi @MarcDonald - The way you've laid this out is perfect.  Unfortunately, the extra space in the coordinates field doesn't work with Map View. If you delete that space, this will work great.  I've included an example Map View to show you how your plug-in works with 4,000 location-enabled journal entries. It's truly brilliant!

<img width="1287" alt="Screenshot 2024-09-26 at 4 53 52 PM" src="https://github.com/user-attachments/assets/996ea2cb-6b7a-4dce-8fae-2d69eabaf181">

Between your plug-in and Map View, Obsidian users have a terrific way to import their Day One journals with the ever-inportant location metadata intact.   Bravo!

**Comment by MarcDonald** [comment]
Wonderful! Glad to hear it's what you need - I've removed that space in [version 1.1.2](https://github.com/MarcDonald/obsidian-day-one-importer/releases/tag/1.1.2) which should be available for you to update to now

**Comment by RobertBreen-cyber** [comment]
Just tested version 1.1.2. It works perfectly. Terrific job!
