### ISSUE TITLE
Periods replacing hyphens in text

### ISSUE THREAD

**Issue by RobertBreen-cyber** [MarcDonald/obsidian-day-one-importer#3]
**Describe the bug**
In a test of importing about thirty journal entries (which worked flawlessly!), I noticed that any hyphenated text (e.g. 30-minutes or e-reader) came over in Obsidian with a period instead of a hyphen (i.e. 30.minutes or e.reader).  Everything else seemed to translate perfectly.

**To Reproduce**

Import a journal entry in Day One with text that includes a hyphen/dash between words.

**Expected behavior**
Expected the hyphenated words to not be altered.

**Desktop (please complete the following information):**

- OS:  Sonoma
- Version  14.5
- Obsidian Version 1.6.7 (Catalyst)

**Comment by MarcDonald** [comment]
Hey @RobertBreen-cyber, thanks for reporting this!

Unfortunately I'm not able to recreate this on my machine (Sonoma 14.5, Obsidian 1.6.7) with this JSON [hyphen-bug.json](https://github.com/user-attachments/files/16324668/hyphen-bug.json) - if possible would you mind commenting with a minimal JSON file with an example entry that has this issue (making sure to strip all private info like location)?

**Comment by RobertBreen-cyber** [comment]
Hi there! I've attached a JSON file to this message with the following text in a journal entry from Day One:

Test of Special-Characters
Test entry of special characters (and words in parentheses).  The following words are hyphenated: age-related, 10-minute and space-cadet. 

(this is a phrase that’s enclosed in parentheses)

After import, the journal entry becomes this in Obsidian:

Test of Special.Characters
Test entry of special characters .and words in parentheses..  The following words are hyphenated: age.related, 10.minute and space.cadet. 

.this is a phrase that’s enclosed in parentheses.

---

Hyphens and parentheses are replaced with periods in Obsidian. I'm on Day One version 2024.14. Let me know if you see something weird in the JSON export file. Thank you!

[Journal.json](https://github.com/user-attachments/files/16324891/Journal.json)

**Comment by MarcDonald** [comment]
Perfect thank you! Looks like when Day One exports it escapes the hyphens and parenthesis, so `Dolore-ex-commodo` comes out as `Dolore\\-ex\\-commodo` - I was able to recreate this with my own Day One exports as well

**Comment by MarcDonald** [comment]
@RobertBreen-cyber This should be fixed in version 1.0.1, thanks for reporting and let me know if there are any other issues!

**Comment by RobertBreen-cyber** [comment]
The update works perfectly! Thank you for creating such a great tool to integrate Day One and Obsidian.
